const fs = require('fs');

const charactersList = [
  {
    id: "tanjiro-kamado-human",
    name: "Tanjiro Kamado (Caçador)",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Família Kamado"],
    styleOrPower: "Respiração do Sol (Hinokami Kagura) / Água",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "A determinação não fraqueja enquanto houver vida!",
    ability: "Dança do Deus do Fogo (Hinokami Kagura)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png"
  },
  {
    id: "tanjiro-kamado-demon-king",
    name: "Tanjiro Kamado (Rei Oni)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Rei dos Demônios", "Família Kamado"],
    styleOrPower: "Tentáculos de Sangue & Imunidade à Luz Solar",
    debutArc: "Castelo Infinito",
    status: "Curado",
    quote: "Eu me tornei o Rei dos Demônios imune ao Sol!",
    ability: "Grito Chocado Supressivo e Tentáculos Ósseos",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png"
  },
  {
    id: "nezuko-kamado-human",
    name: "Nezuko Kamado (Humana)",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Curado",
    quote: "Eu amo muito a minha família!",
    ability: "Cuidado Familiar",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png"
  },
  {
    id: "nezuko-kamado-demon",
    name: "Nezuko Kamado (Oni)",
    gender: "Feminino",
    species: "Oni",
    affiliation: ["Esquadrão de Caçadores", "Família Kamado"],
    styleOrPower: "Kekkijutsu - Sangue Explosivo",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Os humanos devem ser protegidos e salvos!",
    ability: "Explosão de Sangue (Bakketsu)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png"
  },
  {
    id: "zenitsu-agatsuma",
    name: "Zenitsu Agatsuma",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração do Trovão",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Se você só consegue fazer uma coisa, domine essa única coisa!",
    ability: "Primeira Forma: Lampejo do Trovão (Hekireki Issen)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png"
  },
  {
    id: "inosuke-hashibira",
    name: "Inosuke Hashibira",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração da Fera",
    debutArc: "Casa do Tambor",
    status: "Vivo",
    quote: "Avançar! Comandante Inosuke na área!",
    ability: "Quinta Presa: Corte Alucinante",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg"
  },
  {
    id: "kanao-tsuyuri",
    name: "Kanao Tsuyuri",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Mansão Borboleta"],
    styleOrPower: "Respiração da Flor",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "De alguma forma, a minha alma despertou graças a vocês.",
    ability: "Forma Final: Olhos Vermelhos Vermilion (Higan Shugan)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139038-OcOoDUyLEsRn.png"
  },
  {
    id: "genya-shinazugawa",
    name: "Genya Shinazugawa",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Transformação Oni por Ingestão / Empunhadura de Espingarda",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Meu irmão... sempre foi a pessoa mais gentil do mundo.",
    ability: "Assimilação Demoníaca Temporária",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137776-E0QuFD7y19OQ.jpg"
  },
  {
    id: "giyu-tomioka",
    name: "Giyu Tomioka",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Água)"],
    styleOrPower: "Respiração da Água",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Não dê aos outros o poder de decidir se você vive ou morre!",
    ability: "Décima Primeira Forma: Calmaria (Nagi)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b130050-qsLThJs5VIbz.png"
  },
  {
    id: "shinobu-kocho",
    name: "Shinobu Kocho",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Inseto)", "Mansão Borboleta"],
    styleOrPower: "Respiração do Inseto",
    debutArc: "Montanha Natagumo",
    status: "Morto",
    quote: "Posso ser a única espadachim que não consegue cortar cabeças de onis, mas o veneno fará o trabalho.",
    ability: "Dança da Centopéia: Zig-Zag das Cem Pernas",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png"
  },
  {
    id: "kyojuro-rengoku",
    name: "Kyojuro Rengoku",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Chamas)"],
    styleOrPower: "Respiração das Chamas",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Mantenha o seu coração em chamas!",
    ability: "Nona Forma: Rengoku (Chama Purificadora)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png"
  },
  {
    id: "tengen-uzui",
    name: "Tengen Uzui",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Som)"],
    styleOrPower: "Respiração do Som",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Nós vamos vencer de forma extravagante!",
    ability: "Partitura Musical Estratégica",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b136071-99Kexnnn2PiV.png"
  },
  {
    id: "muichiro-tokito",
    name: "Muichiro Tokito",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Névoa)"],
    styleOrPower: "Respiração da Névoa",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Eu nasci para ser feliz!",
    ability: "Sétima Forma: Névoa Obscura (Oboro)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b136069-6PLglx4tETUX.png"
  },
  {
    id: "mitsuri-kanroji",
    name: "Mitsuri Kanroji",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Amor)"],
    styleOrPower: "Respiração do Amor",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Por favor, se nascermos de novo, você se casaria comigo?",
    ability: "Quinta Forma: Amor Hesitante - Garras Trêmulas",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b136072-xVwyRUKdpybi.png"
  },
  {
    id: "obanai-iguro",
    name: "Obanai Iguro",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Serpente)"],
    styleOrPower: "Respiração da Serpente",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Prometo que na próxima vida eu serei um homem digno de você.",
    ability: "Quinta Forma: Serpente Deslizante",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137777-kGViiNyx0wa7.jpg"
  },
  {
    id: "sanemi-shinazugawa",
    name: "Sanemi Shinazugawa",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Vento)"],
    styleOrPower: "Respiração do Vento",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Vou estraçalhar cada um dos demônios que existem!",
    ability: "Primeira Forma: Cortador de Vento da Poeira",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137774-O1iYrnGLB71l.png"
  },
  {
    id: "gyomei-himejima",
    name: "Gyomei Himejima",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Hashira (Rocha)"],
    styleOrPower: "Respiração da Rocha",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Namo Amida Butsu... Que as suas almas descansem em paz.",
    ability: "Quarta Forma: Conquista Volcânica de Rocha",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137778-H4Uzb9cSCvZ6.jpg"
  },
  {
    id: "kanae-kocho",
    name: "Kanae Kocho",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Ex-Hashira (Flor)"],
    styleOrPower: "Respiração da Flor",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Se você puder sorrir para os demônios, talvez um dia vivamos em paz.",
    ability: "Técnica de Lâminas Florais de Seda",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139039-YmIZQzx1HdvY.png"
  },
  {
    id: "sakonji-urokodaki",
    name: "Sakonji Urokodaki",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Ex-Hashira (Água)"],
    styleOrPower: "Respiração da Água",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Se a sua irmã devorar um humano, você deve matá-la e depois cometer seppuku!",
    ability: "Mestre Cultivador de Respiração da Água",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137773-N4O52f73dJKZ.png"
  },
  {
    id: "sabito",
    name: "Sabito",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração da Água",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Vá em frente! Seja um homem!",
    ability: "Corte de Água Fluido",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137809-6Tkle99lCBl8.png"
  },
  {
    id: "makomo",
    name: "Makomo",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração da Água",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Nós amamos muito o Urokodaki-san.",
    ability: "Esquiva Graciosa de Água",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137806-43Lqae34Vzqu.png"
  },
  {
    id: "jigoro-kuwajima",
    name: "Jigoro Kuwajima",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Ex-Hashira (Trovão)"],
    styleOrPower: "Respiração do Trovão",
    debutArc: "Casa do Tambor",
    status: "Morto",
    quote: "Zenitsu, você é o meu orgulho.",
    ability: "Mestre Cultivador da Respiração do Trovão",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137775-WVj9nyVaYo45.png"
  },
  {
    id: "hotaru-haganezuka",
    name: "Hotaru Haganezuka",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Vila dos Ferreiros", "Esquadrão de Caçadores"],
    styleOrPower: "Forja Mestra de Espadas Nichirin",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Vou te matar por quebrar a minha espada!",
    ability: "Polimento Extremo de Lâmina Nichirin",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b138990-E5kiUoLigpyX.jpg"
  },
  {
    id: "kozo-kanamori",
    name: "Kozo Kanamori",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Vila dos Ferreiros"],
    styleOrPower: "Forja de Espadas Nichirin",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Fiz esta espada pensando no estilo único do Tokito-sama.",
    ability: "Forja Especializada Nichirin",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b206331-ss70JxaeUkeU.png"
  },
  {
    id: "kotetsu",
    name: "Kotetsu",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Vila dos Ferreiros"],
    styleOrPower: "Manutenção do Boneco Yoriichi Zeroshiki",
    debutArc: "Vila dos Ferreiros",
    status: "Vivo",
    quote: "Seu fracassado! Continue treinando até vomitar!",
    ability: "Operação de Treinamento Automatizado",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b40851-BChYgBB31gyx.png"
  },
  {
    id: "tecchin-tecchikawahara",
    name: "Tecchin Tecchikawahara",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Vila dos Ferreiros"],
    styleOrPower: "Líder dos Ferreiros",
    debutArc: "Vila dos Ferreiros",
    status: "Vivo",
    quote: "Ferreiros são artistas de lâminas!",
    ability: "Liderança de Artesãos",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b299978-KMYqUZV1ejla.jpg"
  },
  {
    id: "kagaya-ubuyashiki",
    name: "Kagaya Ubuyashiki",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Ubuyashiki", "Líder do Esquadrão"],
    styleOrPower: "Voz Pacificadora / Visão Tática de Liderança",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Meus amados filhos caçadores...",
    ability: "Ressonância Vocal de Acalento",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137808-4yA8XQUDrAho.png"
  },
  {
    id: "amane-ubuyashiki",
    name: "Amane Ubuyashiki",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Ubuyashiki"],
    styleOrPower: "Nenhum",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Estar ao lado do meu esposo até o fim é meu desejo.",
    ability: "Suporte Estratégico",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b221375-cMlefDNTlcD6.jpg"
  },
  {
    id: "kiriya-ubuyashiki",
    name: "Kiriya Ubuyashiki",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Ubuyashiki", "Líder do Esquadrão"],
    styleOrPower: "Comando Estratégico em Tempo Real",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "A batalha do Castelo Infinito deve ser coordenada até o último segundo!",
    ability: "Mapeamento Psíquico por Pássaros Usame",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139460-jA7lAHb17aLL.png"
  },
  {
    id: "kanata-ubuyashiki",
    name: "Kanata Ubuyashiki",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Ubuyashiki"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Vivo",
    quote: "Sejam bem-vindos à Seleção Final.",
    ability: "Assistente da Seleção Final",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b153220-QH10oCcepSdz.jpg"
  },
  {
    id: "hinaki-ubuyashiki",
    name: "Hinaki Ubuyashiki",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Ubuyashiki"],
    styleOrPower: "Nenhum",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Permaneceremos ao lado de nosso pai.",
    ability: "Suporte Familiar",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b167549-1fG4eh5KkmZg.png"
  },
  {
    id: "aoi-kanzaki",
    name: "Aoi Kanzaki",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores", "Mansão Borboleta"],
    styleOrPower: "Respiração da Água (Suporte / Medicina)",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Tive sorte na Seleção Final, por isso fico na Mansão ajudando na recuperação.",
    ability: "Cuidados Médicos e Farmacologia",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b145288-1sZG1vJmysmY.jpg"
  },
  {
    id: "murata",
    name: "Murata",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração da Água",
    debutArc: "Montanha Natagumo",
    status: "Vivo",
    quote: "Eu também sou um caçador de demônios!",
    ability: "Sobrevivência Incrível",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137774-O1iYrnGLB71l.png"
  },
  {
    id: "tamayo",
    name: "Tamayo",
    gender: "Feminino",
    species: "Oni",
    affiliation: ["Independente", "Médica"],
    styleOrPower: "Kekkijutsu - Aroma Enfeitiçante de Sangue / Veneno Anti-Muzan",
    debutArc: "Asakusa",
    status: "Morto",
    quote: "Devolva a vida que você tirou de tantas pessoas, Muzan!",
    ability: "Ilusão por Sangue de Mistletoe & Droga de Humanização",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b138847-rOwIPLKaR5Ux.jpg"
  },
  {
    id: "yushiro",
    name: "Yushiro",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Independente", "Assistente da Tamayo"],
    styleOrPower: "Kekkijutsu - Venda de Invisibilidade e Percepção Visual",
    debutArc: "Asakusa",
    status: "Vivo",
    quote: "Ninguém no mundo é mais bonita que a Tamayo-sama!",
    ability: "Papel de Ocultação Visual e Compartilhamento de Visão",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b138846-i8frJEl8baly.jpg"
  },
  {
    id: "chachamaru",
    name: "Chachamaru (Gato da Tamayo)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Assistente da Tamayo", "Suporte"],
    styleOrPower: "Kekkijutsu - Ocultação & Transporte de Sangue de Oni",
    debutArc: "Asakusa",
    status: "Vivo",
    quote: "Miau! *Transporta soro anti-Kekkijutsu*",
    ability: "Papel de Ocultação e Aplicação de Soro Antidemoníaco",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b268212-cdX6j5xYomyU.jpg"
  },
  {
    id: "muzan-kibutsuji",
    name: "Muzan Kibutsuji",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Rei dos Demônios", "Doze Kizuki"],
    styleOrPower: "Anatomia Mutável / Tentáculos de Sangue de Oni Original",
    debutArc: "Asakusa",
    status: "Morto",
    quote: "Eu sou um ser perfeito próximo à natureza. O que destruo são desastres naturais.",
    ability: "Chicotes de Sangue com Veneno Celular Atômico",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg"
  },
  {
    id: "kokushibo",
    name: "Kokushibo",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 1)"],
    styleOrPower: "Respiração da Lua + Kekkijutsu de Lâminas Crescentes",
    debutArc: "Castelo Infinito",
    status: "Morto",
    quote: "Para quê nasci se nem mesmo consegui me tornar igual a você, meu irmão?",
    ability: "Décima Sexta Forma: Lua Arco-Íris - Lua Meio-Cheia",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b141918-Bfgq88XJFOPz.png"
  },
  {
    id: "doma",
    name: "Doma",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 2)", "Culto do Paraíso Eternal"],
    styleOrPower: "Kekkijutsu - Gelo Criogênico e Lótus Congelante",
    debutArc: "Distrito do Entretenimento",
    status: "Morto",
    quote: "Sentimentos? O que é isso? Nunca senti nada em minha vida inteira!",
    ability: "Jardim de Lótus Congelado & Bodhisattva de Gelo",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b144591-v2yrXtHorZFS.png"
  },
  {
    id: "akaza",
    name: "Akaza",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 3)"],
    styleOrPower: "Kekkijutsu - Desenvolvimento de Agulha de Bússola & Artes Marciais Soryu",
    debutArc: "Trem Infinito",
    status: "Morto",
    quote: "Torne-se um demônio, Kyojuro! Assim você pode lutar para sempre!",
    ability: "Estilo Destruidor: Agulha de Bússola (Compass Needle)",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b141694-0COi0GVXPuEn.png"
  },
  {
    id: "hantengu",
    name: "Hantengu (Corpo Principal)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Divisão de Emoções",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Coitadinho de mim! Por que vocês sempre atormentam um fraco como eu?",
    ability: "Ocultação de Tamanho em Mini-Oni Espremido",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b260323-2zytvxsXp7rG.png"
  },
  {
    id: "sekido",
    name: "Sekido (Emoção da Raiva)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Cetro de Trovão Paralisante",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Eu estou furioso! Vou eletrocutar todos vocês até virarem cinzas!",
    ability: "Descarga Elétrica pelo Cetro Khakkhara",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b86595-BPCdpUefg6gC.jpg"
  },
  {
    id: "karaku",
    name: "Karaku (Emoção da Alegria)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Leque de Folha de Bordo",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Isso é tão divertido! Vamos voar pelos ares!",
    ability: "Ráfaga de Vento Devastadora pelo Leque Uchiwa",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/984.jpg"
  },
  {
    id: "aizetsu",
    name: "Aizetsu (Emoção da Tristeza)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Lança Yari de Projeção",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Que depressivo... Tudo nesta vida me traz tanta tristeza.",
    ability: "Estocadas Múltiplas com Lança Yari Cortante",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137774-O1iYrnGLB71l.png"
  },
  {
    id: "urogi",
    name: "Urogi (Emoção do Prazer)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Garras Aviárias & Ondas Sonoras Destrutivas",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Haha! Que sensação maravilhosa estar nos céus!",
    ability: "Grito Ultra-Sônico e Garras de Águia",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137506-EzqPO6yHvjcK.jpg"
  },
  {
    id: "zohakuten",
    name: "Zohakuten (Emoção do Ódio)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 4)"],
    styleOrPower: "Kekkijutsu - Fusão de Emoções & Dragões de Madeira",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Seus vilões imundos! Intimidação contra os fracos é um pecado imperdoável!",
    ability: "Invocação de Dragões de Madeira e Ondas de Vento e Trovão",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b260323-2zytvxsXp7rG.png"
  },
  {
    id: "gyokko",
    name: "Gyokko",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 5)"],
    styleOrPower: "Kekkijutsu - Vasos Cerâmicos e Invocação Aquática Monstruosa",
    debutArc: "Vila dos Ferreiros",
    status: "Morto",
    quote: "Olhe para a minha sublime arte cerâmica!",
    ability: "Vaso de Prisão de Água & Forma Verdadeira Escamosa",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b205590-mNWuXG5oPw4g.jpg"
  },
  {
    id: "daki",
    name: "Daki (Lua Superior 6)",
    gender: "Feminino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 6)"],
    styleOrPower: "Kekkijutsu - Faixas de Obi Cortantes",
    debutArc: "Distrito do Entretenimento",
    status: "Morto",
    quote: "Eu sou linda e forte! Meu irmão vai matar todos vocês!",
    ability: "Manipulação de Fita Obi Nichirin-Resistente",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139734-ZEy1ccFcwjaK.jpg"
  },
  {
    id: "gyutaro",
    name: "Gyutaro (Lua Superior 6)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 6)"],
    styleOrPower: "Kekkijutsu - Foices de Sangue Venenoso",
    debutArc: "Distrito do Entretenimento",
    status: "Morto",
    quote: "Nós sempre nos protegemos. Se o céu nos amaldiçoar, nós matamos o céu!",
    ability: "Foice de Sangue Venenoso Voador",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139735-o4G63Po27zND.png"
  },
  {
    id: "hinatsuru",
    name: "Hinatsuru",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Kunoichi", "Esposa do Tengen"],
    styleOrPower: "Kunai Carregada de Veneno de Glicínia",
    debutArc: "Distrito do Entretenimento",
    status: "Vivo",
    quote: "Se derrotarmos a Lua Superior, vamos viver como humanos normais.",
    ability: "Disparo de Balestra de Kunais",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b250556-tZ6egykZTk4Y.jpg"
  },
  {
    id: "makio",
    name: "Makio",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Kunoichi", "Esposa do Tengen"],
    styleOrPower: "Combate de Infiltração Ninja",
    debutArc: "Distrito do Entretenimento",
    status: "Vivo",
    quote: "Suma, cale a boca e lute!",
    ability: "Agilidade e Espionagem Shinobi",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b171138-WuRvetNXkHiF.png"
  },
  {
    id: "suma",
    name: "Suma",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Kunoichi", "Esposa do Tengen"],
    styleOrPower: "Combate Ninja",
    debutArc: "Distrito do Entretenimento",
    status: "Vivo",
    quote: "Tengen-sama! Nós vamos morrer!",
    ability: "Resgate e Evasão Ninja",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b145288-1sZG1vJmysmY.jpg"
  },
  {
    id: "kaigaku-human",
    name: "Kaigaku (Humano/Caçador)",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores"],
    styleOrPower: "Respiração do Trovão",
    debutArc: "Casa do Tambor",
    status: "Morto",
    quote: "Eu farei o que for preciso para sobreviver e ser forte!",
    ability: "Segunda a Sexta Forma da Respiração do Trovão",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b165862-G9PpuvlEsfdN.jpg"
  },
  {
    id: "kaigaku-demon",
    name: "Kaigaku (Oni)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Superior 6)"],
    styleOrPower: "Respiração do Trovão Negra + Kekkijutsu Elétrico",
    debutArc: "Castelo Infinito",
    status: "Morto",
    quote: "Eu sirvo quem me valoriza! Não me importo de me curvar a demônios!",
    ability: "Segunda a Sexta Forma do Trovão Negro",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b165862-G9PpuvlEsfdN.jpg"
  },
  {
    id: "enmu",
    name: "Enmu",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Inferior 1)"],
    styleOrPower: "Kekkijutsu - Indução ao Sono Profundo e Fusão com Trem",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Tenha bons sonhos enquanto morre no meu pesadelo...",
    ability: "Sussurro do Sono Hipnótico Profundo",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b139737-1YaFT0Xvxwaz.png"
  },
  {
    id: "rui",
    name: "Rui",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Doze Kizuki (Lua Inferior 5)"],
    styleOrPower: "Kekkijutsu - Teias de Fio de Aranha de Aço",
    debutArc: "Montanha Natagumo",
    status: "Morto",
    quote: "Nossos laços de família são verdadeiros e inquebráveis!",
    ability: "Gaiola de Linhas Vermelhas Cortantes",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b127596-VJjQQk2uWrgM.png"
  },
  {
    id: "temple-demon",
    name: "Demônio do Templo",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Independente"],
    styleOrPower: "Regeneração Demoníaca Inicial",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Tem algo de errado com este garoto... ele usa uma machadinha!",
    ability: "Ataque com Garras Iniciais",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b138812-Imqj3sSfpcso.jpg"
  },
  {
    id: "hand-demon",
    name: "Demônio das Mãos",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Independente (Montanha Fujikasane)"],
    styleOrPower: "Massa Muscular Múltipla de Braços",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Quantos anos se passaram desde que aquele garoto de máscara me prendeu aqui?",
    ability: "Crescimento de Múltiplos Braços Gigantescos",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b137778-H4Uzb9cSCvZ6.jpg"
  },
  {
    id: "swamp-demon",
    name: "Demônio do Pântano",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Independente"],
    styleOrPower: "Kekkijutsu - Dimensão do Pântano Negro",
    debutArc: "Pântano do Sequestrador",
    status: "Morto",
    quote: "Meninas aos 16 anos perdem a maciez, por isso as devoro logo!",
    ability: "Mergulho em Pântano Dimensional Negro",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b138812-Imqj3sSfpcso.jpg"
  },
  {
    id: "tanjuro-kamado",
    name: "Tanjuro Kamado (Pai do Tanjiro)",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Dança Hinokami Kagura Original / Mundo Transparente",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Respire fundo e continue dançando para o Deus do Fogo.",
    ability: "Dança da Hinokami Kagura Sem Exaustão",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png"
  },
  {
    id: "kie-kamado",
    name: "Kie Kamado (Mãe do Tanjiro)",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Tome cuidado na montanha, Tanjiro.",
    ability: "Cuidado Materno",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b196849-xnYBt0Jf5Htf.png"
  },
  {
    id: "takeo-kamado",
    name: "Takeo Kamado",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Eu também quero ajudar a cortar lenha!",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b196852-zzu0xZXJrFr9.png"
  },
  {
    id: "hanako-kamado",
    name: "Hanako Kamado",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Tanjiro, me leva com você!",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b196853-3MBhoPxBTvrN.png"
  },
  {
    id: "shigeru-kamado",
    name: "Shigeru Kamado",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "Volte logo, irmãozinho!",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b196851-r5px2ZuOU9I2.png"
  },
  {
    id: "rokuta-kamado",
    name: "Rokuta Kamado",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Kamado"],
    styleOrPower: "Nenhum",
    debutArc: "Seleção Final",
    status: "Morto",
    quote: "*Dorme nos ombros do Tanjiro*",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b207857-sn24LyeKSrPr.jpg"
  },
  {
    id: "shinjuro-rengoku",
    name: "Shinjuro Rengoku",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Ex-Hashira (Chamas)", "Família Rengoku"],
    styleOrPower: "Respiração das Chamas",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Kyojuro... você lutou bravamente até o fim!",
    ability: "Guarda de Elite do Novo Líder Ubuyashiki",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b193379-54MeZxQdvZ9o.jpg"
  },
  {
    id: "ruka-rengoku",
    name: "Ruka Rengoku",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Família Rengoku"],
    styleOrPower: "Nenhum",
    debutArc: "Trem Infinito",
    status: "Morto",
    quote: "Aqueles que nascem fortes têm o dever de proteger os fracos.",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b193378-dSruD7x4KzQA.jpg"
  },
  {
    id: "senjuro-rengoku",
    name: "Senjuro Rengoku",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Família Rengoku"],
    styleOrPower: "Nenhum (Suporte)",
    debutArc: "Treinamento de Reabilitação",
    status: "Vivo",
    quote: "Mesmo que eu não consiga ser um Hashira, ajudarei com os registros da família.",
    ability: "Pesquisa Histórica da Respiração",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b193380-W10Kx339cY4D.png"
  },
  {
    id: "keizo",
    name: "Keizo",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Mestre do Dojo Soryu"],
    styleOrPower: "Artes Marciais Soryu",
    debutArc: "Castelo Infinito",
    status: "Morto",
    quote: "Hakuji, você vai herdar o meu dojo e cuidar da minha filha!",
    ability: "Estilo Soryu de Combate Desarmado",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b372391-sCs5eizjYrsy.png"
  },
  {
    id: "koyuki",
    name: "Koyuki",
    gender: "Feminino",
    species: "Humano",
    affiliation: ["Passado do Akaza"],
    styleOrPower: "Nenhum",
    debutArc: "Castelo Infinito",
    status: "Morto",
    quote: "Hakuji-san... obrigada por ter me protegido.",
    ability: "Nenhum",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b354440-baufwO1gkKDE.jpg"
  },
  {
    id: "yoriichi-tsugikuni",
    name: "Yoriichi Tsugikuni",
    gender: "Masculino",
    species: "Humano",
    affiliation: ["Esquadrão de Caçadores (Ancestral)"],
    styleOrPower: "Respiração do Sol (Original) + Mundo Transparente",
    debutArc: "Distrito do Entretenimento",
    status: "Morto",
    quote: "Acredito que os que virão depois de nós superarão todas as nossas conquistas.",
    ability: "Estilo da Respiração do Sol de 13 Formas Perfeitas",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b149220-OuBk7B3O6WD6.jpg"
  },
  {
    id: "hairo",
    name: "Hairo (Ex-Lua Inferior 2)",
    gender: "Masculino",
    species: "Oni",
    affiliation: ["Ex-Doze Kizuki (Ex-Lua Inferior 2)"],
    styleOrPower: "Kekkijutsu - Sombras & Armamento Militar Sombrio",
    debutArc: "Treinamento de Reabilitação",
    status: "Morto",
    quote: "Minha vergonha e fúria serão enterradas na escuridão!",
    ability: "Manipulação de Sombras Armadas e Tiroteio Demoníaco",
    avatar: "https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg"
  }
];

fs.writeFileSync(
  'src/data/animes/demon-slayer/characters.json',
  JSON.stringify(charactersList, null, 2),
  'utf8'
);

console.log(`✨ Banco de Dados Corrigido com ${charactersList.length} personagens em characters.json!`);
